name: Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: CI
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        # Run on the latest minor release of Go 1.20:
        go-version: ^1.20
      id: go


    - name: Ensure all files were formatted as per gofmt
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: sysinfo
      run: |
        sudo nft list ruleset
        ip a
        ip r
        ls -l /boot

    - name: Run tests
      run: |
        go test -c github.com/google/nftables
        sudo strace -fvy -s4096 ./nftables.test -test.v -run_system_tests -test.run=TestCtExpect
        #sudo ./nftables.test -test.v -run_system_tests
